routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

use  App\Http\Controllers\Admin\Products\ProductsController;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for the admin area.
| Prefix: /admin
| Middleware: auth auth.admin
|
*/

Route::get('/products', [ProductsController::class, 'index'])->name('admin.products');

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Product extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'price',
        'description',
        'image_url'
    ];

    public function specifications(): HasMany
    {
        return $this->hasMany(ProductSpecification::class);
    }

    public function facts(): HasMany
    {
        return $this->hasMany(ProductFact::class);
    }

    public function getPriceFormattedAttribute(): string
    {
        return "&euro; " . number_format($this->getAttribute('price'), 2, ',', '.');
    }
}

app/Models/ProductFact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class ProductFact extends Model
{
    use HasFactory;

    public $incrementing = false;
    public $timestamps = false;

    protected $fillable = [
        'product_id',
        'content',
        'is_positive'
    ];

    protected $casts = [
        'is_positive' => 'boolean'
    ];

    public function product(): BelongsTo
    {
        return $this->belongsTo(Product::class);
    }
}

app/Models/ProductSpecification.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class ProductSpecification extends Model
{
    use HasFactory;

    public $incrementing = false;
    public $timestamps = false;

    protected $fillable = [
        'product_id',
        'key',
        'value'
    ];

    public function product(): BelongsTo
    {
        return $this->belongsTo(Product::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'password',
        'is_admin',
    ];


    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
        'is_admin' => 'boolean'
    ];
}

app/Http/Controllers/Admin/Products/ProductsController.php
<?php

namespace App\Http\Controllers\Admin\Products;

use App\Http\Controllers\Controller;
use App\Models\Product;
use Illuminate\Http\Request;
use Spatie\QueryBuilder\QueryBuilder;

class ProductsController extends Controller
{
    public function index()
    {
        $products = QueryBuilder::for(Product::class)
            ->allowedFilters('name')
            ->paginate(25);

        return view('admin.products.index', [
            'products' => $products
        ]);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/_layouts/admin.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ config('app.name') }} - Beheer</title>

    <link rel="icon" href="{{ asset('favicon.png') }}">

    <link rel="stylesheet" href="{{ asset('css/app.css') }}" type="text/css">

    @stack('head')
</head>
<body>

<div id="app">

    <div id="sidebar">
        @include('_partials.admin.header')
    </div>

    <div id="content">
        @yield('content')
    </div>
</div>

<script src="{{ asset('js/app.js') }}"></script>
@stack('js')
</body>
</html>

resources/views/_layouts/app.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ config('app.name') }}</title>

    <link rel="stylesheet" href="{{ asset('css/app.css') }}">

    @stack('head')
</head>
<body>

<div id="app">
    @yield('content')
</div>

<script src="{{ asset('js/app.js') }}"></script>
@stack('js')
</body>
</html>

resources/views/_partials/admin/header.blade.php
<div class="vh-100 position-fixed p-3 bg-white h-100 shadow">
    <a href="/admin" class="d-flex pb-3 mb-3 link-dark border-bottom">
        <img class="bi mx-auto" height="70" src="{{ asset('favicon.png') }}" alt="multiversum logo">
    </a>
    <ul class="list-unstyled ps-0">
        <li class="mb-1">
            <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#home-collapse" aria-expanded="true">
               <i class="mdi mdi-format-list-text"></i> Producten
            </button>
            <div class="collapse" id="home-collapse">
                <ul class="btn-toggle-nav list-unstyled ms-4 fw-normal pb-1">
                    <li><a href="{{ route('admin.products') }}" class="link-dark rounded">Overzicht</a></li>
                    <li><a href="#" class="link-dark rounded">Korting</a></li>
                </ul>
            </div>
        </li>
    </ul>
</div>

resources/views/admin/products/index.blade.php
@extends('_layouts.admin')

@section('content')
    <div class="container-fluid">
        <h2>Producten</h2>

        <div class="card shadow">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Naam</th>
                    <th>Prijs</th>
                    <th>Voorraad</th>
                    <th>Acties</th>
                </tr>
                </thead>
                <tbody>
                @foreach($products as $product)
                    <tr>
                        <td><b>{{ $product->id }}</b></td>
                        <td>{{ $product->name }}</td>
                        <td>{!! $product->price_formatted !!}</td>
                        <td>{{ $product->stock ?? 'N/A' }}</td>
                        <td>
                            <i class="mdi mdi-eye-outline"></i>
                            <i class="mdi mdi-pencil-outline ms-2"></i>
                            <i class="mdi mdi-delete-alert ms-2"></i>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@stop